### ISSUE TITLE
DB connections leak in the presence of exceptions

### ISSUE THREAD

**Issue by cite-reader** [drahamim/invenflask#10]
Nearly all database interactions in this application follow a similar pattern to the following example:

```python
def get_staff(staff_id):
    conn = get_db_connection()
    staff = conn.execute('SELECT * FROM staffs WHERE id = ?',
                         (staff_id,)).fetchone()
    conn.close()
    return staff
```

If an exception is thrown for any reason between `conn = get_db_connection()` and `conn.close()` in the above code, the connection will stay alive until the entire application is shut down--potentially at an inopportune moment caused by the pile-up of excessive database connections. The usual recommendation for fixing this is to use the resource inside a `with` block, but the context manager associated with sqlite3 connections is strictly for transaction control, which is _extremely_ unfortunate. The direct fix is to use the old-school `try`/`finally` style:

```python
conn = get_db_connection()
try:
    <do stuff with conn>
finally:
    conn.close()
```

but this is also a perfect use case for a `@needs_db_conn` decorator or similar that handles the pattern in one place. Actually does Flask provide any kind of dependency injection container, because putting external connections in one of those would be ideal.

**Comment by drahamim** [comment]
@cite-reader A quick workaround could be to just wrap it in a function (not go all the way to decorators) 
I'm not sure what dependency injection container means so I can't answer that.
